export enum TransactionStatus {
  AWAITING_PROVIDER_CONFIRMATION = 'AWAITING_PROVIDER_CONFIRMATION',
  AWAITING_REQUESTER_CONFIRMATION = 'AWAITING_REQUESTER_CONFIRMATION',
  DECLINED_BY_PROVIDER = 'DECLINED_BY_PROVIDER',
  DECLINED_BY_REQUESTER = 'DECLINED_BY_REQUESTER',
  ACCEPTED_BY_REQUESTER = 'ACCEPTED_BY_REQUESTER',
}
